<div  class="row"><div  class="col-xl-9 col-lg-12"><div  class="card"><div  class="card-title"> <?php echo t("Maintenance"); ?></div> <div  class="card-content"> <?php if($model["maintenanceModeEnable"]) { ?><div  class="alert alert-warning"> <?php echo t("Maintance mode is enabled!"); ?></div> <div  class="alert alert-warning"> <?php echo t("If you stuck at maintance mode remove .htaccess file and replace it with original.htaccess"); ?></div>  <?php } ?><button  class="button button-danger"  id="maintenance" <?php if((is_bool(  $model['maintenanceModeEnable']?1:0 ) && (  $model['maintenanceModeEnable']?1:0 )) || !is_bool(  $model['maintenanceModeEnable']?1:0 )) { echo " data-state=\"" . ($model['maintenanceModeEnable']?1:0) . "\""; } ?>><?php echo t($model["maintenanceModeEnable"]?"Turn off maintenance mode":"Turn on maintenance mode"); ?></button> <div  class="help-text"> <?php echo t("Maintenance mode turns on a special mode where when the page is turned off, you will still see it."); ?><br /> <?php echo t("The special maintenance htaccess is located in the includes/maintenance.htaccess folder"); ?><br /> <?php echo t("The maintenance mode fallback page is located in include/maintenance.html"); ?><br /> <?php echo t("If you want you can create a page in the views/content/maintenance.view folder and replace the standard html page with maintenance mode"); ?></div> </div> </div> <div  class="card"><div  class="card-title"> <?php echo t("Lock"); ?></div> <div  class="card-content"><form  id="login-setting"  method="post"  action="<?php echo Router::url(); ?>adminv3/system/update_lock/"><div  class="row"><div  class="col-md-3 static-text"><?php echo t("Password"); ?></div> <div  class="col-md-9"><input  type="text" <?php if((is_bool(  $model['password'] ) && (  $model['password'] )) || !is_bool(  $model['password'] )) { echo " value=\"" . ($model['password']) . "\""; } ?>  name="password" /></div> </div> <div  class="row"><div  class="col-md-3 static-text"></div> <div  class="col-md-9"><label><input  type="toggle_swipe"  name="pageLock"  value="1" <?php if((is_bool(  $model['lockEnable'] ) && (  $model['lockEnable'] )) || !is_bool(  $model['lockEnable'] )) { echo " checked=\"" . ($model['lockEnable']) . "\""; } ?> /> <?php echo t("Enable page lock"); ?></label></div> </div> <div  class="row"><div  class="col-md-3"></div> <div  class="col-md-9"><button  type="submit"  class="submit button button-primary"  name="save"><?php echo t('Save'); ?></button>  </div> </div> </form> </div> </div> </div> </div> <script> $("#maintenance").on("click", function(){
        var state = $(this).data("state");
        btnLoading($(this), true);
        manager.get("<?php echo Router::url(); ?>adminv3/system/update_maintenance/", {state: state == 0? 1: 0 }, function (data, isSuccess) {
            if(isSuccess) {
                manager.reload();
            }
        });
    })
</script>